# Generated by Django 4.2 on 2023-04-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforequest',
            name='usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
